### ISSUE TITLE
Licensing and Governance

### ISSUE THREAD

**Issue by lithomas1** [mesonbuild/meson-python#182]
I was looking through the LICENSE files and saw that meson-python is copyrighted by Quansight Labs.

The main question that I have about this is: "Do I still own the code that I commit?" 
This is very important to me, since I'm not OK with signing away ownership of my code to a commercial company for free. 

It would also be nice if open-source contributions were recognized in the license file. (Maybe a new line, like ``Copyright 2022, the meson-python developers``(like numpy) or ``Copyright 2022 Open source contributors`` like pandas).

Secondly, the relationship between Quansight and meson-python should probably be clarified. 

Is there any kind of support that I can expect from Quansight, or is it just copyrighted by Quansight since it was created by someone who works there. 
Ideally, in the docs/website somewhere, I should be able to figure out the affiliations(if any) of all the maintainers.

Thanks.

**Comment by rgommers** [comment]
> 

The main question that I have about this is: "Do I still own the code that I commit?"

**Comment by rgommers** [comment]
> The main question that I have about this is: "Do I still own the code that I commit?"
> This is very important to me, since I'm not OK with signing away ownership of my code to a commercial company for free.

Yes, definitely, 100% agree! You own all the code for your contributions. I'll note that the copyright line is not leading here, you always own the copyright for the code you write, unless you have signed a CLA or other paperwork that says otherwise. 



> It would also be nice if open-source contributions were recognized in the license file. (Maybe a new line, like `Copyright 2022, the meson-python developers`(like numpy) or `Copyright 2022 Open source contributors` like pandas).

Agreed, I'll open a PR for this.

Also related: gh-168, that should help too.



> Secondly, the relationship between Quansight and meson-python should probably be clarified.
> 
> Is there any kind of support that I can expect from Quansight, or is it just copyrighted by Quansight since it was created by someone who works there.

It's the latter. This project was very much needed, and Quansight Labs funded the initial development. @FFY00 and I are both employed there. In the last couple of months in particular it has gotten a lot more contributions from other folks, so we need to reflect that in the license file. We definitely want to run `meson-python` as a regular community-driven open source project. Every contributor owns the copyright to their contributions, and becoming a maintainer should only depend on interest and history/quality of contributions to the project, and not to employment.

> Ideally, in the docs/website somewhere, I should be able to figure out the affiliations(if any) of all the maintainers.

I would say that this should not be relevant. My working on this project is not contingent on my employment status, just like my maintainership of NumPy and SciPy isn't (I worked on it for a decade as a volunteer before joining a Python-focused company). `meson-python` is important to the wider scientific Python ecosystem, so it falls in that same category.

What I would say though is that the docs may reflect sizeable contributions in either engineering time or financial support. Something like Sponsors and Institutional Partners on https://numpy.org/about/. What do you think about that?

**Comment by lithomas1** [comment]
> > Ideally, in the docs/website somewhere, I should be able to figure out the affiliations(if any) of all the maintainers.
> 
> I would say that this should not be relevant. My working on this project is not contingent on my employment status, just like my maintainership of NumPy and SciPy isn't (I worked on it for a decade as a volunteer before joining a Python-focused company). `meson-python` is important to the wider scientific Python ecosystem, so it falls in that same category.
> 
> What I would say though is that the docs may reflect sizeable contributions in either engineering time or financial support. Something like Sponsors and Institutional Partners on https://numpy.org/about/. What do you think about that?

Thanks for the quick reply, and sorry for the delay in responding. I think having a sponsors/institutional partners section is good (we also do this for pandas). The updates to the LICENSE also look good to me.

**Comment by FFY00** [comment]
Yes, I think this is a good idea.
