### ISSUE TITLE
Scripts are not installed when installing from sdist

### ISSUE THREAD

**Issue by ssssam** [mesonbuild/meson-python#220]
My package `calliope-music` installs an executable named `cpe`, declared as follows:

```
configure_file(
    input: 'main.py.in',
    output: 'cpe',
    configuration: cdata,
    install_dir: get_option('bindir'))
```

The generated bdist_wheel package includes the script:

```
> unzip -l dist/calliope_music-8.1-py3-none-any.whl |grep cpe
     1058  11-20-2022 11:48   calliope_music-8.1.data/scripts/cpe
````

and when installing the wheel with `pip install`, the script ends up in `~/.local/bin` for me. All good.

The sdist does not contain the script however:

```
> tar tf dist/calliope_music-8.1.tar.gz|grep cpe
calliope_music-8.1/examples/special_mix/test.cpe
calliope_music-8.1/scripts/cpe-enter
```

I suppose this expected, as it should be generated from `main.py.in` during package build.

However, when installing from sdist, there is no `~/.local/bin/cpe` created.

I am not yet sure what is the cause. I guess the next step is to get detailed logging for the install-from-sdist process and look for clues.

**Comment by ssssam** [comment]
Log of `pip3 -v -v -v install . ` in a clone of https://gitlab.com/samthursfield/calliope/

[log.txt](https://github.com/mesonbuild/meson-python/files/10049814/log.txt)

Afterwards, no `cpe` script is found  anywhere in `~/.local`.

**Comment by ssssam** [comment]
Ah, I  see useful warnings in this log:

```
  + meson install --destdir /home/sam/src/calliope/.mesonpy-vgcwl8_f/install
  WARNING Using heuristics to map files to wheel, this may result in incorrect locations
  WARNING File could not be mapped to an equivalent wheel directory: /home/sam/src/calliope/.mesonpy-vgcwl8_f/install/usr/share/tagcloud/calliope-viewer.gresource (/usr/share/tagcloud/calliope-viewer.gresource)
  WARNING File could not be mapped to an equivalent wheel directory: /home/sam/src/calliope/.mesonpy-vgcwl8_f/install/usr/bin/cpe ({prefix}/bin/cpe)
  WARNING File could not be mapped to an equivalent wheel directory: /home/sam/src/calliope/.mesonpy-vgcwl8_f/install/usr/bin/calliope-viewer ({prefix}/bin/calliope-viewer)
```

**Comment by ssssam** [comment]
This may be a dup of https://github.com/mesonbuild/meson-python/issues/115 ?

**Comment by dnicolodi** [comment]
Is this a Python script or something else? If it is a Python script, the recommended way to distribute it is a a `console-script` entry point.

**Comment by rgommers** [comment]
> This may be a dup of #115 ?

It looks a little different, because your file does end up in the right location from a wheel it sounds like. gh-115 should have fixed itself by now, says my comment there.

> I suppose this expected, as it should be generated from `main.py.in` during package build.

To include generated files into sdists, use the `fs.exists` pattern as in https://github.com/mesonbuild/meson-python/issues/159#issuecomment-1265962676. 

We should document that pattern, this will become an FAQ I think.

**Comment by henryiii** [comment]
Keep in mind, `console-script`'s have specially written shebang lines that make sure they get the correct interpreter regardless of environment. While if you were to put some `.py` file inside scripts, it would not pull the correct interpreter all the time. `scripts` is really only for standalone binaries.

Pip also makes a venv, unless told not to. I have seen it use a locally cached version before. `pip cache purge` might help?

**Comment by eli-schwartz** [comment]
@henryiii wrong, scripts are supposed to have their shebang rewritten for the target python: https://packaging.python.org/en/latest/specifications/binary-distribution-format/#recommended-installer-features

The wheel spec suggests this if the script shebang is otherwise irreparably broken, i.e. it starts with the exact bytes: `b'#!python'` (which cannot be resolved to a file on disk. But, from memory, pip and setuptools `setup.py install` and probably other installer tools as well handle this for any shebang ending in `python` and an optional version number, as either the last path component or as an argument to e.g. `/path/to/usr/bin/env`.

**Comment by henryiii** [comment]
Ahh, didn't remember that. Couldn't meson-python rewrite scripts that begin with a normal shebang line to `b'#!python'` before making the wheel, like setuptools? Pip and installer are following the specification - scripts must begin with exactly `b'#!python'`. Without processing by meson-python, the scripts placed in `scripts` can't be run as scripts outside of an installed setting... Actually, I think that's exactly what you suggested at the end of your message.

The one (maybe) tricky part is you need to only process Python scripts, but you could require an existing shebang, maybe even as `!/usr/bin/env (python|pypy)*` (not required on Unix, but that form is usually ideal and is processed specially by Python for Windows, IIRC).

**Comment by eli-schwartz** [comment]
Yeah, when I say unfix those scripts I mean use the high-level concept setuptools does and check if the script has a shebang matching `^#!.*[/ ]python[0-9.]*(\s+.*)?$` (so, anything matching `/path/to/pythonXXX` or `/path/to/prog pythonXXX` with additional optional flags to python itself -- this is actually similar to the setuptools regex, but mine doesn't match on `/path/to/notpython`), and if so, rewrite it to the specification's `#!python`.

When running `meson install` such scripts may have been `configure_file()`d with the same "fix the absolute location" logic in which case env wouldn't match, but it's trivial to account for that anyway. I didn't think about pypy though, good point.

**Comment by henryiii** [comment]
For posterity, worth also noting that PEP 660 (editable installs) does not support `scripts`, with the recommendation being to use `console-script`'s instead.

**Comment by eli-schwartz** [comment]
"not support" is a strong way to put it. The PEP simply says that the PEP doesn't define anything about them. In that respect, `scripts` would be no different from the metadata, including the list itself of `console-script`s. Namely, that since they aren't editable-aware, they won't update from the build tree.

The PEP specifically states that you can use `scripts`, in fact -- but with a condition:
> Package authors are encouraged to use `console_scripts`, make their `scripts` tiny wrappers around library functionality, or [...]

And indeed, `console_scripts` is just a standard for autogenerating tiny wrappers. If your scripts don't change frequently enough to need editable support for being updated from the source/build tree, that might be okay.

(But also there is no reason the scripts couldn't be replaced in an editable wheel with a small python script that runs `import sys, os; os.execv('/path/to/source/tree/script-source', sys.argv[1:])`.)
