### ISSUE TITLE
Python 3.7 on Windows and macOS arm64 build failures using meson-python 0.11.0 with cibuildwheel 

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#222]
On Windows, building for win32 fails with
```
Program python found: YES (C:\Users\runneradmin\AppData\Local\Temp\cibw-run-dbnhe2vj\cp37-win32\build\venv\Scripts\python.exe)
Need python for 64-bit, but found 32-bit
        
..\..\meson.build:24:3: ERROR: Python dependency not found
```
it may be a cibuildwheel issue or a Meson issue. Full log here https://github.com/dnicolodi/python-siphash24/actions/runs/3517527064/jobs/5895402010

On macOS, building succeeds but test fail. The test pass when the package is not built with cibuildwheel. No idea what is going on as it seems that the test process segfaults. Maybe a linking issue. Full log here https://github.com/dnicolodi/python-siphash24/actions/runs/3517527064/jobs/5895402097

On Linux, linking issue:
```
FAILED: siphash24.cpython-37m-x86_64-linux-gnu.so
        cc  -o siphash24.cpython-37m-x86_64-linux-gnu.so siphash24.cpython-37m-x86_64-linux-gnu.so.p/meson-generated_siphash24.pyx.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,--start-group subprojects/libcsiphash-1/src/libcsiphash-1.a -L/opt/_internal/cpython-3.7.13/lib -lpython3.7m -Wl,--end-group
        /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: cannot find -lpython3.7m
```
it may be Python 3.7 specific. Again not seen when building without cibuildwheel, maybe related to the setup used in the manylinux container. Full log here https://github.com/dnicolodi/python-siphash24/actions/runs/3517527064/jobs/5895401917

**Comment by henryiii** [comment]
Side comment: When Meson fails, we should raise SystemExit, not throw an exception. Pip/build report a mess when there's an uncaught exception from the build hooks, while SystemExit is handled gracefully without nearly as much extra reports about missing build hooks and changed exceptions. The actual failure is printed by Meson.

**Comment by henryiii** [comment]
Is this an extension or an app? You should not be linking to Python on macOS/linux if it's an extension.

That Windows failure is supposed to be building a 32-bit wheel, so guessing it's either meson or meson-python not respecting the attempt to build for 32-bit? It does find the 32-bit Python then complains when it's 32-bit (which is what it is supposed to be).

**Comment by dnicolodi** [comment]
> Is this an extension or an app? You should not be linking to Python on macOS/linux if it's an extension. The libs are intentionally deleted from the manylinux images to stop users from trying to link to them.

It is an extension. Meson takes care of the linking, when needed. I don't do it explicitly. Interestingly, it is a problem only for Python 3.7 in cibuildwheel. I've no idea what's going on.

> That Windows failure is supposed to be building a 32-bit wheel, so guessing it's either meson or meson-python not respecting the attempt to build for 32-bit? It does find the 32-bit Python then complains when it's 32-bit (which is what it is supposed to be).

The Windows issue I think is due to cibuildwheel not setting up things for Meson to find the MSVC compiler. I'm trying to setup the correct environment variables from outside to see if this fixes cibuildwheel.

**Comment by dnicolodi** [comment]
> The Windows issue I think is due to cibuildwheel not setting up things for Meson to find the MSVC compiler. I'm trying to setup the correct environment variables from outside to see if this fixes cibuildwheel.

The one solution I've tried https://github.com/bus1/cabuild/tree/main/action/msdevshell does not work.

**Comment by henryiii** [comment]
Are you using the action? There's a report that by using the bash shell in the aciton this breaks Meson's discovery. I think we can fix it by using the native shell and splitting the action up (though, why does this break meson? CMake and setuptools are just fine as it is).

Meson should not be putting in `-lpython3.7(m)`, that's a bug. You can't link to Python's libs. That will cause segfaults on macOS and libraries not found on manylinux. It will work when building locally, since you are using the same patch release of Python that you built with, so it will work (unless you upgrade Python to a new patch release without rebuilding)

**Comment by henryiii** [comment]
That rather scares me - is Meson being tested on Python 3.12a2? Distutils has been removed there. I thought the point of moving to Meson was to be ready for distutils' removal?

If that's the built-in distutils, it wouldn't horribly surprise me, as it's usually filtered by setuptools, and would explain why it would be Python version specific. https://github.com/pypa/setuptools/blob/59ee4980a0f49ea610e26a1aca104334ae03d140/setuptools/_distutils/command/build_ext.py#L736-L789

Hmm, see https://github.com/pypa/setuptools/blob/59ee4980a0f49ea610e26a1aca104334ae03d140/setuptools/_distutils/command/py37compat.py#L6. See https://github.com/pypa/distutils/issues/9.

**Comment by dnicolodi** [comment]
The fact that distutils is going away is know, but there are reasons why Meson depends on it. @eli-schwartz is the one that has the whole picture and working on a solution. You may want to discuss the details with him.

**Comment by dnicolodi** [comment]
cibuildwheel uses bash in GitHub Actions and this puts the GNU compilers on the `$PATH` making a mess for Meson. The solutions for having MSVC compilers on the path do not work for this reason. It seems that cibuildwheel and Meson simply do not mix. One way around is to use the Mingw compilers adding the required configuration to `meson.build`, but this does not allow to build win32 wheels, I think.

**Comment by henryiii** [comment]
Did you try my pipx suggestion? That will avoid bash on Windows.

**Comment by rgommers** [comment]
> SciPy uses cibuildwheel. Did you bump into any of these issues? Don't you build for these platforms?

On Windows we use Mingw-w64 for 64-bit build, and currently we don't build for 32-bit Python on Windows due to the lack of a suitable compiler toolchain (one is in progress, also Mingw based). We haven't had any problems on macOS. 

Code:
- https://github.com/scipy/scipy/blob/main/.github/workflows/wheels.yml
- https://github.com/scipy/scipy/tree/main/tools/wheels

**Comment by rgommers** [comment]
`universal2`: no point in that, best to let it die. just put thin binaries on PyPI I'd say, that's what numpy/scipy/etc do. If you have a user who needs it, point them to `delocate`, which provides a `delocate-fuse` tool that just does the right thing.

**Comment by dnicolodi** [comment]
Still, I think there may be a real bug in meson-python there: with the cibuildwheel setup the wheel tags are wrong.

**Comment by eli-schwartz** [comment]
If both MSVC and the MingGW compilers are on the path, which one should Meson choose, and why? Which one should other build systems choose, and why?



> That rather scares me - is Meson being tested on Python 3.12a2? Distutils has been removed there. I thought the point of moving to Meson was to be ready for distutils' removal?

Meson historically relies on distutils for 2 things:
- figuring out whether the *found python* thinks it needs to link to libpython
- checking whether Debian's patched python with patched `sys.path` has patched distutils to adapt to the patch, but left sysconfig broken

In both cases, the use of distutils is limited to a probe script that dumps json to stdout describing the capabilities of the found python. And in one of those cases, we were limited by "whatever Debian does", which is beyond frustrating but there you have it.

We do intend to fix this before python 3.12 final, and ideally as soon as possible for alpha testing, but the main point is that whether or not Meson uses it isn't something that individual packages like SciPy need to care about.

But "be ready for distutils' removal" is a complex topic, and the main issue that many meson-python adapters have is less about the removal of distutils from the stdlib, and more about what that means for setuptools' release velocity, API stability, and the infeasibility of maintaining numpy.distutils. The use of either distutils or setuptools isn't healthy for large projects especially, because of various limitations which mainly boil down to "use a real, battle-tested build system that supports introspection, parallel builds, custom build rules that aren't just open-coded in python, etc."
Having an `import distutils` may or may not be a hindrance to these goals, and as it happens, isn't one.

There's a quick hack to make this work on python 3.12 alpha, simply install setuptools as a build dependency. This is of course a *hack*, not a solution, which is why it will not be needed for the final release. I've already been looking into what is needed here.

**Comment by dnicolodi** [comment]
> Did you try my pipx suggestion?

Just now. It works to build the amd64 binaries. I haven't tried to build both the x86 and amd64. Thank you!

**Comment by henryiii** [comment]
But does it fix Windows? That's what I'd like to know before making a PR to cibuildwheel to split the action.

**Comment by dnicolodi** [comment]
Oh sorry, I thought the context was clear, it works for building the Windows amd64 wheels.

**Comment by henryiii** [comment]
Ahh, of course, thinking about universal2 due to convo above 😜. Okay, will see what can be done in cibuildwheel.

**Comment by dnicolodi** [comment]
I think I found a real bug: meson-python does not generate the right wheel tags when cibuildwheel tries to compile the arm64 or universal2 wheels. @henryiii can you point me to the code in cibuildwheel that sets up the environment for these platforms?

**Comment by dnicolodi** [comment]
Never mind, found it https://github.com/pypa/cibuildwheel/blob/2e6cbe2435ef410156319c98625002ed76e08785/cibuildwheel/macos.py#L219-L232 . And meson-python does not do what cibuildwheel expects:
```python
>>> str(mesonpy._tags.Tag())
'cp310-cp310-macosx_10_15_x86_64'
>>> os.environ['_PYTHON_HOST_PLATFORM'] = "macosx-11.0-arm64"
>>> str(mesonpy._tags.Tag())
'cp310-cp310-macosx_10_15_x86_64'
```

**Comment by henryiii** [comment]
This should be controlled by `ARCHFLAGS`, ideally (it does set both).

**Comment by henryiii** [comment]
IIRC, that was mostly necessary to try to make 3.8 work, since 3.8's a little weird due to ARM support being experimental with 3.8.

**Comment by dnicolodi** [comment]
`ARCHFLAGS` does not change what Python reports. `_PYTHON_HOST_PLATFORM` changes what `sysconfig.get_platforms()` reports. The problem is that I based my implementation of the wheel tag code on `packaging` which uses `platform.mac_ver()` to derive the platform tag on macOS.`platform.mac_ver()` is not affected by the environment variables. This is fine for `packaging` (maybe?) because it is used mostly for generating the tags for installing wheels not for building them thus overwriting the platform makes little sense.

**Comment by henryiii** [comment]
It seems a little error-prone to have one way to specify the target arch's (`ARCHFLAGS`) and another way to set the platform tags (`_PYTHON_HOST_PLATFORM`, which looks private). And `_PYTHON_HOST_PLATFORM` is already ignored when it comes to the target macOS version. Cibuildwheel does not bother to put the correct value here since setuptools computes it from `MACOSX_DEPLOYMENT_TARGET` anyway. IMO, doing the same thing with the platform also makes sense: if you are targeting ARM, it should modify the target platform to be Arm, not pretend to be Arm via `_PYTHON_HOST_PLATFORM`. It's more of a setuptools bug that this has to be set too, IMO.

**Comment by dnicolodi** [comment]
Uh? `MACOS_DEPLOYMENT_TARGET` contains only the macOS version, not the platform, AFAIK. `setuptools` uses `wheel` to build wheels and `wheel` uses `sysconfig.get_platform()` to get the platform tag https://github.com/pypa/wheel/blob/814c2efe8e40051039c5a6de6945e04ecdd162ee/src/wheel/bdist_wheel.py#L47-L56

**Comment by dnicolodi** [comment]
The problem with `ARCHFLAGS` is that it contains flags for the compiler and they can be arbitrary, AFAIU.

**Comment by henryiii** [comment]
`calculate_macosx_platform_tag` ignores the macOS version when `MACOSX_DEPLOYMENT_TARGET` is set. `ARCHFLAGS` is how a target arch is set in setuptools, and you can check it for `-arch <target>`. If you want to follow setuptools (which is where ARCHFLAGS comes from, AFAIK, I don't think it's more general), then you already should be using it to see what binaries to build. My only suggestion beyond that is to use it to also set the wheel tag, rather than setting the wheel tag to the host Python, which is what setuptools incorrectly does, and cibuildwheel works around by forcing `_PYTHON_HOST_PLATFORM`. A universal build of Python is not always making universal wheels, etc, so this is a hack that would be nice to not require for meson-python, I think. If they are mismatched, you'll produce broken wheels.

pybind/cmake_exmpple and scikit-build have used ARCHFLAGS for years, as does Maturin AFAICT: https://github.com/PyO3/maturin/blob/82d584bb6c2d6d605720ff27daa4c86b9baf03b9/src/build_options.rs#L530.

**Comment by dnicolodi** [comment]
meson-python doesn't do anything with `ARCHFLAGS`. I thought it is some xtools thing. Building arm64 wheels on macOS x86_64 with cibuildwheel most likely does not work then as nothing tells Meson to use the right compiler flags. @rgommers how does SciPy do it?

**Comment by henryiii** [comment]
If you want to be bug-compatible with setuptools/wheel then `ARCHFLAGS` should instruct meson what macOS archs to target, and `_PYTHON_HOST_PLATFORM` to set the wheel tags. I think `ARCHFLAGS` should be used for both, ideally. This is how the CMake based tools use it to tell CMake what archs to target, I'd expect there's something similar for Meson:
https://github.com/scikit-build/scikit-build/blob/88fafd7943037f1ff57efb53d3b0c8e3d66455f8/skbuild/constants.py#L52-L56

**Comment by eli-schwartz** [comment]
So ARCHFLAGS is just the actual "right compiler flags"?

**Comment by henryiii** [comment]
ARCHFLAGS is `-arch x86_64` if you are (cross)compiling to Intel, `-arch arm64` for Apple Silicon, or `-arch x86_64 -arch arm64` if you are targeting universal. I don't think I've seen other things in there, but we usually check check if for `-arch <something>` patterns and process any that we find (in my case, usually by setting `CMAKE_OSX_ARCHITECTURES` to a semicolon separated list). It might be processed by Xcode, I'm not seeing it mentioned in setuptools/distutils, though regardless, I think checking it and respecting it if it's set is the right thing to do.

I see `VSCMD_ARG_TGT_ARCH` for Windows in Distutils/Setuptools, which serves roughly the same purpose except for Windows, I think. I'll investigate that further later.

**Comment by rgommers** [comment]
> if you are targeting ARM, it should modify the target platform to be Arm, not pretend to be Arm via `_PYTHON_HOST_PLATFORM`. It's more of a setuptools bug that this has to be set too, IMO.

I think this is just a case of terminology. There are two common ways of talking about build/host/target, as explained near the top of https://mesonbuild.com/Cross-compilation.html#cross-compilation. This environment variable is named consistently with how Meson uses terminology: _host machine is the machine on which the compiled binary will run._

Setting `_PYTHON_HOST_PLATFORM` is a bit hacky and longer term we should find a nicer way - but it's not too much of a problem right now I'd say, if it gives us the desired effect.

> I think `ARCHFLAGS` should be used for both, ideally

This does not seem like a good idea to me, for two reasons: 

1. This couples two things (wheel tags, compiler flags) that should not be so closely coupled
2. Environment variables aren't great to begin with compared to CLI flags, and this one isn't very standard.

It looks like only reason we're even talking about `ARCHFLAGS` is `universal2`, which is a macOS thing that got way more prominence than it deserves from Python (it makes little sense for wheels on PyPI, and the main reasons we got it are low effort during introduction, and the person involved in defining the work caring more about the very niche py2app use case than about the needs of average users).

I'd much prefer if we supported `universal2` the sane way: by compiling separate thin wheels (either regular + cross, or two native builds on separate machines), and then combining them. And otherwise via a special CLI flag to meson-python, that adds the requires `-arch x86_64` or `-arch arm64` flags to existing CFLAGS/CXXFLAGS/FFLAGS env vars.

**Comment by rgommers** [comment]
> @rgommers how does SciPy do it?

SciPy uses Cirrus CI - which offers free M1 CI for open source projects, and is quite nice to use - so we produce `arm64` wheels on Cirrus CI and `x86-64` wheels on GitHub Actions. We do not provide `universal2` wheels and don't plan to; if we did want to, the way to do it would be to grab the two thin wheels and combine then with [delocate-fuse](https://github.com/matthew-brett/delocate/blob/653b9734894df3a0b57f1f7f5602b7566f723aff/delocate/cmd/delocate_fuse.py).

**Comment by henryiii** [comment]
It will work if they are kept separate, though I still think setting `_PYTHON_HOST_PLATFORM` is a bit internal and is supposed to be what Python reports itself as - it's perfectly fine to build an Intel wheel or a Arm wheel from a universal build of Python. It's a bit of a hack due to `wheel` reading this variable, while `ARCHFLAGS` controls the compilation.

> It looks like only reason we're even talking about `ARCHFLAGS` is `universal2`

You need `ARCHFLAGS` when cross compiling, right? `ARCHFLAGS="-arch arm64"` is how you detect that you need to build AS binaries even if your build of Python is Universal2 - or Intel, which is also valid for building AS cross-compiled binaries (that's what we use for CPython 3.8, actually). If you parse it from `_PYTHON_HOST_PLATFORM`, and hope that that was set, then that's even worse IMO than the two settings (`_PYTHON_HOST_PLATFORM` for wheel tags and `ARCHFLAGS` for binary target), and it also still support universal2, since that's contained in `_PYTHON_HOST_PLATFORM`, so I'm not sure what this meant.

Actually speaking of Universal2, regardless of opinions, it will be seen as a bug (at least as a downside vs. setuptools or hand-rolled solutions), I think, if meson-python does not support all targets from cibuildwheel out of the box. Though clearly documenting that universal2 is not supported, and documenting how to use delocate-fuse hopefully would be fine. I need some link I can put on the Issues that are opened in cibuildwheel when it fails. :)

FYI, you can find people with strong opinions on both sides of Universal2. The CPython core dev that developed the tags for Apple Silicon [strongly disagreed with producing native wheels at all](https://github.com/pypa/cibuildwheel/issues/473):

> As mentioned elsewhere I'd prefer to see "universal2" wheels everywhere and no architecture specific wheels.

**Comment by rgommers** [comment]
> You need `ARCHFLAGS` when cross compiling, right?

No, you need to use a [cross file](https://mesonbuild.com/Cross-compilation.html). Right now SciPy uses it [like so](https://github.com/scipy/scipy/blob/main/.github/workflows/wheels.yml#L214-L220):
```
meson setup --cross-file $(pwd)/tools/wheels/cross_arm64.txt build
python -m pip wheel -w dist -vvv --config-settings builddir=build .
```

> Actually speaking of Universal2, regardless of opinions, it will be seen as a bug (at least as a downside vs. setuptools or hand-rolled solutions), I think, if meson-python does not support all targets from cibuildwheel out of the box. 

If so, let's add it with a CLI flag. Although I don't agree it's a bug if there's literally a one-liner to do it with `delocate`. Nor would I call that unsupported really. It's a more generic way of doing it, which works the same whether you're cross-compiling or using native M1 CI.

> Though clearly documenting that universal2 is not supported, and documenting how to use delocate-fuse hopefully would be fine. I need some link I can put on the Issues that are opened in cibuildwheel when it fails. :)

Yep, I need that too, just opened an issue: https://github.com/matthew-brett/delocate/issues/169.

> FYI, you can find people with strong opinions on both sides of Universal2. The CPython core dev that developed the tags for Apple Silicon [strongly disagreed with producing native wheels at all](https://github.com/pypa/cibuildwheel/issues/473):

That's exactly the person who is the maintainer of `py2app` that I had in mind. And who has not responded to binary size comparisons, nor requests from the NumPy team and others for better use cases. And was the main point arguing for introducing universal2. So hard to take that as a counterpoint really. Ignoring more or less doubling download and disk space requirements, at the expense of users (especially in countries with less advanced infrastructure or unlimited internet plans), mainly to make the `py2app` use case just slightly easier is not okay imho, so I will not be supporting universal2 wheels for the scientific projects I work on. As a stopgap measure when no one had an M1 machine it was maybe defensible. At this point it arguably just should not exist, just like we don't have a format for 32+64 bit wheels for Windows, or x86-64 + aarch64 for Linux. 

I'm fine with supporting `universal2` in meson-python, but not with new, nonstandard environment variables. Meson's design philosophy is to avoid those, in favor of CLI arguments. Which I've come to appreciate - it's more explicit and easier to reason about and deal with when debugging end user bug reports.

**Comment by dnicolodi** [comment]
I think I can summarize the results of my experiment with the `siphash24` package as follows:

- Meson requires the MSVC compilers to be available in `$PATH`. This is a surprise for people switching from setuptools to meson-python because the former does not have this requirement. This should be documented somewhere. See #224.

- Meson attempts to link extensions modules for Python 3.7 on Linux with `libpython37m` and this fails on the `manylinux` docker images. I don't know whether linking with libpython is wrong here or what else is going on. I'll investigate this further and open an issue with Meson if needed.

- The extension modules built by Meson for Python 3.7 in the cibuildwheel setup cause a segfault when loaded. I don't have many ideas about what may cause this, but I'll try to look into this further.

- meson-python does not support the way setuptools (and other build tools do following its lead) uses to to enable cross-architecture build on macOS. See #225

**Comment by henryiii** [comment]
We need to support the existing environment variables in order to work with all existing tooling. And while it's fine to also support an explicit command line argument, you have to support an environment variable in order to allow tools like cibuildwheel, multibuild, and Conda-build to exist. They can set an environment variable, you might even convince them to add a new variable, but they can't add a new command line option unless every single backend (including setuptools) supports it (or at least ignores it).

As I've said, if you link to libpython, you get segfaults. I'm nearly sure that's why 3.7 on macOS is segfaulting. On linux, the library is deleted, so you get a missing library error instead of a segfault; if you build on one machine and send it to another machine with a different patch release of Python, I think you'll get a segfault too. So I think that's the same problem, just with different effects.

**Comment by henryiii** [comment]
We are not talking about universal2. We are talking about cross-compilation. Building ARM on Intel runners, mostly, though eventually the other direction will be important too. conda-forge does cross-compilation. And I'm sure there are other tools, in house tools (like wheelhouse builders), etc. My point is that you should at respect the existing standards, even if you offer a "nicer" alternative.

`--config-settigns` cannot be used (and least as the only method), because tools like scikit-build-core and now meson-python will reject keys-value pairs they do not accept.

**Comment by rgommers** [comment]
> We are not talking about universal2. We are talking about cross-compilation.

Ah sorry, I did not get that.

> My point is that you should at respect the existing standards, even if you offer a "nicer" custom alternative.

That's a fair point. I'm not sure at this point that this is a "standard" though. It feels like a hack inherited from setuptools. Cross-compilation has never been properly supported in Python land. Is this at all documented anywhere?

**Comment by dnicolodi** [comment]
Linking issue identified and reported here https://github.com/mesonbuild/meson/issues/11097 Meson PR on the way.

**Comment by rgommers** [comment]
Would you mind updating it to something descriptive that looks more correct to you @dnicolodi? "Failures across the board" is too vague. I semi-regularly go through a whole backlog, so having titles that are descriptive is useful to me.

> are due to a bug in Meson

We do have a `dependency-bug` for that - it signals that it's an issue that may affect `meson-python` users, but has to be solved elsewhere.

**Comment by dnicolodi** [comment]
The idea was to close this bug once the root cause of the failures was identified. I opened specific bugs for the identified issues, see https://github.com/mesonbuild/meson-python/issues/222#issuecomment-1323610463 and https://github.com/mesonbuild/meson-python/issues/222#issuecomment-1324214338 however this didn't stop people from continuing to comment on this way too vague issue thus I felt it did not make sense to close it in favor of the more specific ones.

**Comment by rgommers** [comment]
Okay, let's close this then - I'll edit the description to point to those two comments.

**Comment by dnicolodi** [comment]
@henryiii How does cibuildwheel setup the environment for compiling x86 Windows binaries in a x86_64 build machine? Does it do something special to get the right compiler or does it expect to just work? Right now I need to run cibuildwheel twice with different `$PATH` to have Meson pick the right compiler, but it would be nice if there were a way to avoid this.
