### ISSUE TITLE
muon compatibility

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#323]
I think it would make sense to explore compatibility with [muon](https://sr.ht/~lattis/muon/) and see how viable that is.

It currently implements Meson 0.64 and has support for most of the features. To get it to work with meson-python, it might just need to export the necessary metadata.
https://muon.build/releases/edge/docs/status.html

**Comment by dnicolodi** [comment]
Unless I read the linked page in the wrong way, it seems that the only method in the Meson's `python` module implemented by `muon` is `fint_installation()`. This is not really enough for most (all?) meson-python users, which expect to be able to build Python extension modules without too much plumbing on their side.

**Comment by FFY00** [comment]
Yes, but that's not that difficult to fix.

**Comment by dnicolodi** [comment]
Sure, very few things are difficult to fix, given enough resources. If someone implements the required interfaces in muon, then it is just matter to allow a `$MESON` environment variable to point to the Meson implementation. However, muon opted for a command line interface not compatible with meson, thus some conditionalization of the commands meson-python runs will be necessary.

**Comment by annacrombie** [comment]
@dnicolodi muon now has `muon meson` which is a cli compatibility layer.  It translates meson flags into muon ones:

```
@kuro > ~/src/c/muon muon meson setup --prefix /asd --debug -Dfoo=bar build1 /path/to/src
args: ['muon', '-C/path/to/src', 'setup', '-Dprefix=/asd', '-Ddebug=true', '-Dfoo=bar', '/home/lattis/src/c/muon/build1']
```

**Comment by dnicolodi** [comment]
Sure, but still you need to add one more parameter o the command line.

**Comment by annacrombie** [comment]
Or you could set MESON="muon meson".  Also, symlinking `muon` to `meson` will make muon automatically use the cli compat layer.

**Comment by dnicolodi** [comment]
I don't think supporting a `$MESON` environment variable that contains more that the path to the Meson executable is feasible. It would be impossible to know whether `MESON="/path/to the/meson/tool"` should be interpreted as the `/path/to/` executable run with `the/meson/tool` as first parameter or as a path `/path/to the/meson/tool` containing a space character. No, we are not going to sh lex the environment variable value, so no amount of quoting and escaping is going to fix this.

If you symlink `muon` to `meson` and the executable provides the exact same interfaces as `meson`, then we can already close this issue.

**Comment by FFY00** [comment]
I mean, there's already a module for that in the standard library :rofl:

https://docs.python.org/3/library/shlex.html

**Comment by FFY00** [comment]
But I agree, shlex-ing it would be too messy. The easier solution would be to just check if it's Meson or muon and add the `meson` argument on muon.

**Comment by eli-schwartz** [comment]
shlex'ing the value of a variable that wasn't always defined to contain shell quoting is potentially risky. It also means that to specify a path to meson that contains spaces, you'd have to play with multiple levels of quoting. It also doesn't intuitively work on windows, because shlex will do `sh` lexing, not `cmd` lexing.

I think supporting it as either a symlink or detecting when basename is `muon` and appending `meson` to it, is the superior approach vs. trying to pass quoting around.

> it seems that the only method in the Meson's `python` module implemented by `muon` is `fint_installation()`. This is not really enough for most (all?) meson-python users, which expect to be able to build Python extension modules without too much plumbing on their side.

Well, all really.
- I don't think there's such thing as a python extension module that doesn't want to be built with the `py.extension_module()` support for correctly defining the SO_EXT, so using the generic `shared_module()` function is unlikely to be something that actually happens.
- whether pure or compiled, you want `py.get_install_dir()` instead of inventing your own custom options (and get_install_dir already has its own module option for free, if the autodetection fails).

> Yes, but that's not that difficult to fix.

But indeed, the muon rationale here has been "get find_installation partially working, document the module as partially implemented, to cover a few common use cases of retrieving the installation as a script runner". The rest is up to whether people find it interesting to work on.

(It would be super cool to get additional support here.)

...

There are a couple other issues that may be larger. One is handling installed files without the meson-specific json introspection files (this seems rather complicated to add to muon). The other issue is machine file support. Cross compilation could be left for now to meson.py, I guess...

**Comment by rgommers** [comment]
`MESON="muon meson"` now works after gh-458. There's no issue with spaces I believe; if the string is not a file then it's interpreted as the name of the executable to call.

The content of this issue is still relevant, especially the last comment above. There is probably nothing left to do inside meson-python though, so perhaps we should close this issue and open one on the muon repo about status and help needed for improving Python support?

**Comment by dnicolodi** [comment]
> `MESON="muon meson"` now works after [gh-458](https://github.com/mesonbuild/meson-python/issues/458).

I don't think that this works: there is no lexing, so an executable names "muon meson" would be searched in the path.

**Comment by rgommers** [comment]
Oops, indeed - I should have verified first. We do now have the `MESON` environment variable, so it'd be a two line patch to add this:

> The easier solution would be to just check if it's Meson or muon and add the `meson` argument on muon.

It's not going to help many end users yet because of the limited Python support in muon, but one could also argue that that's a chicken and egg problem. I'd be fine with adding the patch to make `MESON=muon` work. We can't really test that in the test suite though, so we can also leave it until it becomes actually useful to someone.

**Comment by dnicolodi** [comment]
meson-python relies on introspection data exported by Meson. Using `muon` with meson-python would require having `muon` export introspection data exposing the same information. I don't see this happening any time soon, and the meson-python maintainers definitely do not have resources to dedicate to implement it.

**Comment by rgommers** [comment]
This seems fine to close indeed. If and when `muon` adds support for all the `intro-*.json` metadata we need, it's easy enough to revisit this.
