### ISSUE TITLE
Missing interpreter dependency on Cython modules

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#327]
Cython by default uses private API on CPython, see https://github.com/cython/cython/issues/5275, meaning that modules built without defining `CYTHON_LIMITED_API` are only compatible with the CPython version they were built against. We fail to reflect that in the wheels.

This is really really bad because `CYTHON_LIMITED_API` is only experimental and only available in Cython pre-releases, meaning **there's no practical way to ship a stable Cython wheel**. You'd have to build one wheel for each patch version of CPython...

This is not documented anywhere currently, but most relevant information can be found in https://github.com/cython/cython/blob/31e9bb73988fd6c77bcc419d702df748feb24b4a/Cython/Utility/ModuleSetupCode.c.

**Comment by FFY00** [comment]
It seems that ABI resulting from private API is stable-ish, so modules should be compatible.

I think it's reasonable for when it breaks, as it is quite rare, for the maintainers to just update the release though. That would still be nice to document.

**Comment by dnicolodi** [comment]
I don't understand the issue: all Python extension modules can be imported by Python interpreters with the same ABI as the one they were compiled for, unless they use the stable ABI. Python guarantees that the ABI does not change for releases with the same minor version. This is exactly why we put the interpreter minor version in the wheel tags. There is nothing specific about Cython. Recent issues with Python 3.12 and Cython are due to the fact that there are no ABI stability guarantees for Python alpha releases.

**Comment by rgommers** [comment]
Cython uses private API rather than only public CPython C API, which makes this a bit different. There is some "don't do that .... but we must do that for performance" discussion going on, but it's really between Cython and CPython.

**Comment by dnicolodi** [comment]
API is encoded in the headers, ABI is encoded in the object files. If API changes, you cannot compile Cython code. If ABI changes you cannot run the extension modules. Once you compile some Cython extension modules, your ability of using them is only limited by the ABI compatibility. CPython guarantees ABI compatibility for releases with the same minor version.

**Comment by eli-schwartz** [comment]
From my understanding, the issue here is that CPython guarantees that `Py*` API is stable, and `_Py*` API is internal therefore "no promises"...

... and that the logical conclusion of this is that ABI resulting from the former is stable across library soname (minor releases), and ABI resulting from the latter is once more "no promises".

Stable:
```
$ nm -D /usr/lib/libpython3.11.so.1.0 | grep ' Py' | wc -l
1082
```
Unstable:
```
$ nm -D /usr/lib/libpython3.11.so.1.0 | grep ' _Py' | wc -l
571
```

In theory, the only way to get at unstable ABI is to use unstable API or have it proxied by safe public API that passes data between two ABIs that know how to cooperate. So you are technically free to break it whenever you want, because it cannot hurt. In practice, this is probably one of those things you don't want to mess with because you'll inevitably get it wrong at least once and break software that wasn't doing things they weren't supposed to. "Just don't change the ABI" is a conservative, safe rule of thumb.

"Unofficially, ABI resulting from private API is stable-ish" sounds like a good way of putting it. :D

**Comment by dnicolodi** [comment]
I don't know how official the position is, but CPython guarantees ABI stability also for the private API for releases with the same minor version.

**Comment by FFY00** [comment]
It's official, via PEP 6, but that still leaves room for CPython to break ABI if needed (eg. to fix a bug, or to fix a security issue). Impact is considered, and ABI surface that can only result from usage of the private API is definitely ranked as much lower impact than breaking ABI correspondent to the public API.
