### ISSUE TITLE
Path to package

### ISSUE THREAD

**Issue by ragonneau** [mesonbuild/meson-python#391]
Hi,

I have a package for Python and MATLAB that shares the same Fortran sources. The arborescence of my package is as follows.
```
my_project/
    sources/
        *.f, *.f90, ...
    python/
        my_project/
            __init__.py
            main.py
            meson.build
    matlab/
        ...
    pyproject.toml
    meson.build
```

I am switching from `numpy.distutils` to `meson-python`. My problem: I cannot find an equivalent to the `package_dir` argument that allowed me to place my Python package in a subfolder (here named `python`).

The file `my_project/meson_build` contains for the moment `subdir('python/my_project')`, but then running
```bash
python -m pip install .
```
does not install the package `my_project`. Instead, it creates a folder `python` in `site-packages` that contains `my_project`. Is there a workaround as of today that I missed?

Thank you very much,
Tom.

**Comment by dnicolodi** [comment]
meson-python works in a way very different from distutils and setuptools. What is installed and where depends entirely on what the `meson.build` files in your project instruct Meson to install. The `subdir()` Meson function instruct Meson to execute the content of `meson.build` in specific subdirectories, thus is related to the source layout and not to where the code is going to be installed.

If Python source code is installed in `python/my_project/` I supposed you have a `py.install_sources()` call in your `meson.build` with a `subdir: 'python/my_project'` argument or something equivalent. Without seeing the content of the `meson.build` files is impossible to be more precise. If you want to install the Python source code in the `python/my_project` directory as a `my_project` package, the `meson.build` file in the same directory needs to contain something like:
```meson
py = impot('python').find_installation(pure: false)
py.install_sources(
    '__init__.py',
    'main.py',
    subdir: 'my_project',
)
```
where the `pure: false` argument is because I expect you want to place a Python compiled extension is the same package.

However, you don't need the `meson.build` in the subdirectory or to have a subdirectory named in the same way as the Python package in the `python` directory. I prefer flatter directory structures, unless required, and Meson allows you to organize the source code like this:
```
my_project/
    sources/
        *.f, *.f90, ...
    python/
        __init__.py
        main.py
    matlab/
        ...
    pyproject.toml
    meson.build
```
with this content in `meson.build`:
```meson
py = impot('python').find_installation(pure: false)
py.install_sources(
    'python/__init__.py',
    'python/main.py',
    subdir: 'my_project',
)
```

**Comment by ragonneau** [comment]
Hi @dnicolodi,

Thank you very much for your detailed reply. I only misunderstood the `subdir` argument of `extension_module` and `install_sources`. I modified them all from `python/my_project` to `my_project`, and things are working beautifully.

Thank you very much for your kind help,
Tom.
