### ISSUE TITLE
0.13.0 changes `compile-args` `config_settings` API incompatibly

### ISSUE THREAD

**Issue by mgorny** [mesonbuild/meson-python#409]
Prior to 0.13.0, the `compile-args` option to `config_settings` dict used to take `meson compile` arguments. Now it takes `ninja` arguments that aren't 100% compatible with the previous syntax.

For example, we are currently passing user-provided options using the `--ninja-args=` passthrough, i.e.:

```python
ninjaopts = shlex.split(os.environ["NINJAOPTS"])
config_settings = {
    "compile-args": ["-v", f"--ninja-args={ninjaopts!r}"],
}
```

With 0.13.0 we'd have to pass instead:

```python
config_settings = {
    "compile-args": ["-v"] + ninjaopts,
}
```

This is particularly problematic because it suddenly breaks existing deployments, and requires additional knowledge of meson-python prior to invoking the PEP517 build backend.

Original bug report: https://bugs.gentoo.org/904677

**Comment by mgorny** [comment]
The relevant commit is d491766ebf3fbde261c423ba8e76153a5597550f (thanks @ionenwks).

CC @thesamesam

**Comment by eli-schwartz** [comment]
Changed in #328, note that:
- `meson compile` arguments are valid ninja arguments
- ninja `-k0`, `-d <debugmode>` or `-w <warningmode>` are valid ninja arguments but invalid meson compile arguments
- meson compile supports longopts which you probably don't want to use anywhere, I don't know why meson supports them either tbh but :shrug:

Passing args in via --ninja-args was the only valid way to pass -k -d -w from NINJAOPTS to meson compile, so if you did try handling that then this is indeed now broken; it could be solved by just passing ninjaopts in directly.

OOC I wonder if anyone was actually setting anything other than -j / -l inherited from MAKEOPTS. :D

**Comment by eli-schwartz** [comment]
This could possibly be wrapped by meson-python -- by parsing out --ninja-args and inserting its value back in.

**Comment by dnicolodi** [comment]
> This is particularly problematic because it suddenly breaks existing deployments, and requires additional knowledge of meson-python prior to invoking the PEP517 build backend.

Thank you for reporting this issue. This usage of `compile-args` was not envisioned when #328 was discussed. However, I'm not sure, that even with this additional information we would have taken a different decision. Especially considering that 0.12.0 was release without any documentation regarding the usage of `compile-args` and any other mechanism to pass options to the build process. meson-python is still in beta and, while we do our best to keep backward incompatible changes to a minimum, we reserve to break some minor things when adjusting meson-python behavior to better cover its intended primary use cases.

As @eli-schwartz writes, passing the user arguments directly to `compile-args` without the `--ninja-args=` wrapping should work in practice in almost all cases with both meson-python 0.12 and 0.13. While the compatibility interface proposed by @eli-schwartz is an option, I would prefer to do not add backward compatibility kludges unless strictly required.

Do you have the need to pass arguments to `ninja` that are not valid arguments for `meson compile`? Would releasing a meson-python 0.13.1 with the arguments translation machinery help you? It would not help if you need to support all version of meson-python (as your initial report suggests).

**Comment by mgorny** [comment]
Our problem is that we need to pass user-specified Ninja flags through somehow, and we really don't want to do things like checking if they're valid inline `meson compile` args or not. I can live with just passing them inline conditionally to meson-python version. However, I'd like to make sure that this was intentional and isn't going to change again before we add more complexity.

**Comment by dnicolodi** [comment]
The change was intentional. Currently I don't see a reason why we would change this again. I really don't see anyone passing any command line argument to ninja that is not part of the subset also supported by `meson compile`, thus, if I would you, I would just drop the `--ninja-args=` wrapping for all version of meson-python. In the linked Gentoo bug report, the passed flags are `-j30 -l0` which would work just fine. However, I miss the context required to determine whether it is likely that someone wants to specify other command line arguments, but I don't think that any other makes sense if what is being done is compiling python packages.

**Comment by mgorny** [comment]
I think I used `--ninja-args` for a specific reason back when I did it but I'm afraid I don't recall anymore what it were. I'll just make this conditional to meson-python version to avoid breaking anything.

**Comment by dnicolodi** [comment]
Backward compatibility with the most likely used arguments passed to `compile-args` has been preserved, but this somehow niche use case broke. The arguments accepted in `config_settings` were not documented when 0.12.0 was released. Therefore I feel that there weren't any guarantee about how they applied to the build process. For this reason, because @mgorny seem to be able to fix this on the consumer side, and because there aren't any other reports of things breaking, I'm closing this. We can reconsider this later, if needed.
