### ISSUE TITLE
Debug builds contain incorrect relative paths

### ISSUE THREAD

**Issue by ngoldbaum** [mesonbuild/meson-python#440]
I'm not sure if this is an issue with numpy's meson-python usage or an issue that meson-python can fix for all projects, so please feel free to close if we should fix this in numpy's meson configuation.

When I build numpy with debug symbols, the resulting numpy installation contains paths to source files that are correct for the build directory but incorrect for the installed distribution.

Installing numpy's main branch with:

```
$ python -m pip install . -v --no-build-isolation -Csetup-args="-Dbuildtype=debug"
```

Will successfully build and install numpy. However, if you try to run numpy under a debugger, it won't be able to find the source code unless the search path is fixed manually:

```
○  gdb --args $(pyenv which python) -c "import numpy as np; np.array([1, 2, 3])"
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/nathan/.pyenv/versions/3.10.9-debug/bin/python...
(gdb) break PyArray_FromAny
Function "PyArray_FromAny" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (PyArray_FromAny) pending.
(gdb) r
Starting program: /home/nathan/.pyenv/versions/3.10.9-debug/bin/python -c import\ numpy\ as\ np\;\ np.array\(\[1,\ 2,\ 3\]\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, PyArray_FromAny (op=<float at remote 0x7ffff6b8f1f0>, newtype=0x0, min_depth=0, max_depth=0, flags=0, context=0x0) at ../../numpy/core/src/multiarray/ctors.c:1509
1509	../../numpy/core/src/multiarray/ctors.c: No such file or directory.
(gdb) set substitute-path ../../numpy /home/nathan/Documents/numpy/numpy
(gdb) n
1510	    npy_dtype_info dt_info = {NULL, NULL};
```

**Comment by rgommers** [comment]
Thanks for the report @ngoldbaum. I suspect that this is a Meson issue, rather than a meson-python one. I don't think we do anything nonstandard in the NumPy build to cause this. I quickly searched the Meson issue tracker, but came up empty. Perhaps this report triggers a memory for someone; if not I can do some more digging later.

**Comment by eli-schwartz** [comment]
This shouldn't have anything to do with meson either -- the debug section of the resulting compiled binary object should have two fields:
- `DW_AT_name`, containing the input filename as passed to the compiler (meson writes out build rules containing relative paths, hence ../../numpy/core/ )
- `DW_AT_comp_dir`, containing the working directory of the compiler, which the input filename in the event of a relative path is considered relative *to*


If I had to hazard a wild guess as to the cause, the original compilation working directory is invalid and gdb cannot figure out the relationship between it and working source code. This may be because pip created a temporary copy of the entire source tree (some versions did that) or it may be because the builddir was deleted and gdb is not sure that it isn't a symlink or something. I was able to reproduce the issue locally with a test project by deleting the build directory on its own.

**Comment by ngoldbaum** [comment]
Thanks for the hint about the build directory getting deleted, that's the problem. I see in the `meson-python` [docs](https://meson-python.readthedocs.io/en/latest/reference/config-settings.html?highlight=build%20directory#cmdoption-arg-builddir) that if I set `builddir` explicitly when I build numpy, the build directory should get left behind. And indeed, it does, and that fixes the issue.

I'll make sure this gets discussed in the numpy developer guide. 

Ideally we'd be able to use editable builds for this but in practice that doesn't work for me because I need to build other projects against the numpy editable build and getting that to work will require some changes to the numpy. For now we need to make it clear to contributors that a smooth debugging experience requires a persisted build directory.

**Comment by bmerry** [comment]
I've also run into this issue. The behaviour seems to be quite different, depending on whether -Cbuilddir is used. Without it, the name of the (ephemeral) build directory gets baked into the DWARF Directory Table e.g. it will have entries like `../../.mesonpy-quscxr6p/build/../../src`. When I specify builddir=build, it doesn't seem to go up and down the tree any more, and the corresponding entry is just `../src`, which should then be usable with gdb for any build directory that's at the same nesting level.
