### ISSUE TITLE
Add an alias for an editable debug build?

### ISSUE THREAD

**Issue by virtuald** [mesonbuild/meson-python#672]
In the documentation, editable installs are done via

```
$ pip install -e . --no-build-isolation \
    -Csetup-args=-Dbuildtype=debug \
    -Cbuild-dir=build-dbg
```

... but that's annoying. Having a helper command that meson-python installs that executes this for you would be useful and prevent issues such as https://github.com/mesonbuild/meson-python/issues/512

A command for setting up editable installs would also be able to set the build-dir using the abi tag, and probably other useful things (I'm sure I'll think of more things as I start using this)...

And yes, every user could create their own script to run this. But why not do it once for everyone, that seems to be the meson philosophy anyways?

**Comment by virtuald** [comment]
That's fair, but I would argue that much of the time if you're doing an editable install then you're likely going to be interested in debugging -- and https://meson-python.readthedocs.io/en/latest/how-to-guides/debug-builds.html has that exact command that I was referencing. It would be nice if there was an easy way to do that.

However, it does seem like spin would likely be a better place to do it, though having yet another wrapper around things is weird.

**Comment by eli-schwartz** [comment]
> though having yet another wrapper around things is weird.

Interestingly, this is something that bothers me a lot about the current python ecosystem. People are extremely... tunnel-minded... about having "one way to do it" and how every package *must* build with the same pip incantation, so build backends have an aversion to providing integrated frontends.

Then it turns out the frontends aren't good enough, or have bad features, so people end up writing backend-specific frontends targeted at specific features, which also wrap *other* frontends. I still don't understand the utility of poetry, hatch, pdm, etc.

It's an ecosystem-wide issue, dunno what the answer is.

**Comment by rgommers** [comment]
> and https://meson-python.readthedocs.io/en/latest/how-to-guides/debug-builds.html has that exact command that I was referencing.

Note that that's really outdated (I should get around to deleting it). These are the relevant docs: https://mesonbuild.com/meson-python/how-to-guides/editable-installs.html



> if you're doing an editable install then you're likely going to be interested in debugging

It's actually very rare in my experience; most users of editable installs want them for IDE integration for pure Python code.

**Comment by virtuald** [comment]
I'm a strong believer in "simple things should be simple and complex things should be possible". When developing a native library, a debug build is often something you want and should be an easy thing to do.
